crud/urls.py
from django.urls import path
from .views import Index,TableView,ProfileCreate,ProfileDelete,ProfileUpdate

app_name = 'crud'

urlpatterns = [
    path('',Index.as_view(),name='home'),
    path('detail',TableView.as_view(),name='table'),
    path('create',ProfileCreate.as_view(),name = 'create'),
    path('delete/<int:pk>/',ProfileDelete.as_view(),name = 'delete'),
    path('update/<int:pk>/',ProfileUpdate.as_view(),name = 'update'),
]

datastore/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls',namespace = 'crud')),
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crud/models.py
from django.db import models

# Create your models here.
class PersonalDetails(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    number = models.CharField(max_length=10)
    address = models.CharField(max_length=255)

crud/forms.py
from django.forms import models
from .models import PersonalDetails

class PersonalDetailsForm(models.ModelForm):
    class Meta:
        model = PersonalDetails
        fields = ['name','email','number','address']

crud/views.py
from django.shortcuts import render
from django.views.generic import CreateView,ListView,DetailView,DeleteView,TemplateView,UpdateView
from .forms import PersonalDetailsForm
from django.urls import reverse,reverse_lazy
from .models import PersonalDetails
# Create your views here.

class Index(TemplateView):
    template_name = 'crud/index.html'


class ProfileCreate(CreateView):
    template_name = 'crud/index.html'
    form_class = PersonalDetailsForm
    success_url = reverse_lazy('crud:table')


class ProfileDelete(DeleteView):
    model = PersonalDetails
    success_url = reverse_lazy('crud:table')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

class ProfileUpdate(UpdateView):
    template_name = 'crud/update.html'
    form_class = PersonalDetailsForm
    model = PersonalDetails
    success_url = reverse_lazy('crud:table')
    queryset = PersonalDetails.objects.all()

class TableView(ListView):
    template_name = 'crud/detail.html'
    form_class = PersonalDetailsForm
    queryset = PersonalDetails.objects.all()

crud/templates/crud/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rochak Dhakal</title>
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" /> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  
  <!-- Internal Section Start-->
    <section class="major-body-section">
      <div class="container main-content-wrap">
      <form action="{% url 'crud:home' %}">
            <button type="submit" class="btn btn-primary btn-sm ">Home</button>
        </form>
      <br>
        <div class="table-background table-teal">
          <table class="table table-striped">
            <thead>
              <tr>
{#                <th scope="col">#</th>#}
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Number</th>
                <th scope="col">Address</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>

            <tbody>
                {% for detail in object_list %}
              <tr>
{#                <th scope="row">1</th>#}
                <td>{{ detail.name }}</td>
                <td>{{ detail.email }}</td>
                <td>{{ detail.number }}</td>
                <td>{{ detail.address }}</td>

                  <td>
                      <div class="row">
                      <form method="post" action="{% url 'crud:delete' detail.pk %}" class="col-md-6">
                      {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                      </form>
{#                      <span>#}
                      <form method="get" action="{% url 'crud:update' detail.pk %}" class="col-md-6">
                      {% csrf_token %}
                        <button type="submit" class="btn btn-success">Update</button>
                      </form>

{#                      </span>#}
                      </div>
                  </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </section>

  <!-- Internal Section  End-->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous"></script> -->
  
  
</body>

</html>

crud/templates/crud/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rochak Dhakal</title>
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  
  <!-- Internal Section Start-->
  <section class="major-body-section">
    <div class="container main-content-wrap-form">
      <form method="post" action="{% url 'crud:create' %}">
          {% csrf_token %}
        <div class="form-group">
          <label for="formGroupExampleInput">Name</label>
          <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Name" name="name" required>
        </div>
        <div class="form-group">
          <label for="formGroupExampleInput2">Email</label>
          <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Email" name="email" required>
        </div>
        <div class="form-group">
          <label for="formGroupExampleInput2">Number</label>
          <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Number" name="number" required>
        </div>
        <div class="form-group">
          <label for="formGroupExampleInput2">Address</label>
          <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Address" name="address" required>
        </div>
        <br>
        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
          </form>
        <br>
        <form action="{% url 'crud:table' %}">
            <button type="submit" class="btn btn-success btn-lg btn-block">View Data</button>
        </form>
    </div>
  </section>


  <!-- Internal Section  End-->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous"></script>
  
   
</body>

</html>

crud/templates/crud/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rochak Dhakal</title>
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

  <!-- Internal Section Start-->
  <section class="major-body-section">
    <div class="container main-content-wrap-form">
         <form action="{% url 'crud:home' %}">
            <button type="submit" class="btn btn-primary btn-sm ">Home</button>
        </form>
        <br>
      <form method="post">
          {% csrf_token %}
        <div class="form-group">
          <label for="formGroupExampleInput">Name</label>
          <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Name" name="name" value="{{ object.name }}">
        </div>
        <div class="form-group">
          <label for="formGroupExampleInput2">Email</label>
          <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Email" name="email" value="{{ object.email }}">
        </div>
        <div class="form-group">
          <label for="formGroupExampleInput2">Number</label>
          <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Number" name="number" value="{{ object.number }}">
        </div>
        <div class="form-group">
          <label for="formGroupExampleInput2">Address</label>
          <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Address" name="address" value="{{ object.address }}">
        </div>
        <br>
        <button type="submit" class="btn btn-primary btn-lg btn-block">Update</button>
      </form>
        <br>
        <form action="{% url 'crud:table' %}">
            <button type="submit" class="btn btn-success btn-lg btn-block">Table</button>
        </form>

    </div>
  </section>


  <!-- Internal Section  End-->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous"></script>


</body>

</html>